name: GitHub Actions Demo
run-name: Examining issue from ${{ github.actor }}
on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]
jobs:
  # Label-Customer-Issues
  #   Labels new issues and pull requests if the author is not
  #   a member of the repository's organization, or the owner of
  #   the repo if not owned by an organization.
  Label-Customer-Issues:
    runs-on: ubuntu-latest
    steps:
      - name: Label-Customer-Issues
        uses: fulghum/first-interaction@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-label: "customer-issue"
          pr-label: "contribution"
          exclude: dependabot, dependabot2
