name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [issues]
jobs:
  # Label-Customer-Issues
  #   Labels new issues and pull requests if the author is not
  #   a member of the repository's organization, or the owner of
  #   the repo if not owned by an organization.
  Label-Customer-Issues:
    runs-on: ubuntu-latest
    steps:
      - name: Label-Customer-Issues
        uses: fulghum/first-interaction@main
        with:
          issue-label: "customer-issue"
          pr-label: "contribution"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          exclude: dependabot, dependabot2
