name: GitHub Actions Demo
run-name: Applying labels to issue from ${{ github.actor }}
on:
  # NOTE: You must use pull_request_target (and not pull_request), because
  #       pull_request runs in the context of the forked repo, and will not
  #       have permissions to label the PR. pull_request_target runs in the
  #       context of the base repo, and will have permissions to label the PR.
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]

jobs:
  # Label-Customer-Issues
  #   Labels new issues and pull requests if the author is not
  #   a member of the repository's organization, or the owner of
  #   the repo if not owned by an organization.
  Label-Customer-Issues:
    runs-on: ubuntu-latest
    steps:
      - name: Label-Customer-Issues
        uses: fulghum/first-interaction@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-label: "customer-issue"
          pr-label: "contribution"
          exclude: dependabot, dependabot2
